version: '3.8'

services:
  frontend:
    # App de GESTIÓN de reservas (React)
    # ACCESO: http://<IP_Servidor>:8081
    image: public.ecr.aws/d3a6d4r1/cam/reserve:frontend-v1.1
    container_name: frontend_prod
    ports:
      - "8081:80"
    environment:
      - REACT_APP_API_BASE_URL=http://central_reserve:3050
    restart: always
    networks:
      - app-network
    depends_on:
      - central_reserve

  website:
    # Sitio WEB para CLIENTES (Astro)
    # ACCESO: http://<IP_Servidor>:80  (o solo http://<IP_Servidor>)
    image: public.ecr.aws/d3a6d4r1/cam/reserve:website-latest
    container_name: website_prod
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
    depends_on:
      - central_reserve

  central_reserve:
    # Backend (API)
    # No necesita 'ports' porque la comunicación es interna
    image: public.ecr.aws/d3a6d4r1/cam/reserve:backend-v1.1
    container_name: central_reserve_prod
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=restaurant_db
      - DB_SSLMODE=disable
    restart: always
    networks:
      - app-network
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    # Base de datos
    image: postgres:15-alpine
    container_name: postgres_prod
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d restaurant_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 